### Задание 1

In [1]:
import numpy as np

1.1

In [2]:
a = np.array([i for i in range(12,24)])
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

1.2

In [3]:
a.reshape(12,1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [4]:
a.reshape(6,2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [5]:
a.reshape(4,3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [6]:
a.reshape(3,4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [7]:
a.reshape(2,6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

1.3

In [8]:
a.reshape(6,-1)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [9]:
a.reshape(4,-1)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [10]:
a.reshape(3,-1)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [11]:
a.reshape(-1,4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [12]:
a.reshape(-1,3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

1.4 
Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным? - Нет

1.5

In [13]:
a_rn = np.random.randn(3,4)
a_rn

array([[-1.31643701, -1.44333519, -2.023504  ,  1.55483168],
       [ 0.95741277, -0.58125013, -0.69579897, -1.24354414],
       [-0.25581869,  1.76029307,  0.01447576, -0.94520693]])

In [14]:
a_rn.size

12

In [15]:
b = a_rn.reshape(1,-1)
b

array([[-1.31643701, -1.44333519, -2.023504  ,  1.55483168,  0.95741277,
        -0.58125013, -0.69579897, -1.24354414, -0.25581869,  1.76029307,
         0.01447576, -0.94520693]])

In [16]:
b.size

12

In [17]:
a_rn.flatten()

array([-1.31643701, -1.44333519, -2.023504  ,  1.55483168,  0.95741277,
       -0.58125013, -0.69579897, -1.24354414, -0.25581869,  1.76029307,
        0.01447576, -0.94520693])

1.6

In [18]:
a = np.arange(20,1,-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [19]:
b = np.array([np.arange(20,0,-2)])
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

В чем разница между массивами a и b?
Массив а это список чисел, а массив b это список строк.

1.7

In [20]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [21]:
b = np.ones((3,2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [22]:
v = np.vstack((a,b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
v.size

10

1.8

In [24]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
A = a.reshape(4, -1)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [26]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [27]:
B = np.dot(A,At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [28]:
B.size

16

In [29]:
np.linalg.det(B)

0.0

Получится ли вычислить обратную матрицу для матрицы B и почему?
- Нет, т.к. определитель = 0 

1.9

In [30]:
np.random.seed(42)

In [31]:
c = np.random.randint(0,16,16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

In [32]:
C = c.reshape(4,4)
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [33]:
D = B + (C * 10)
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [34]:
np.linalg.det(D)

-28511999.999999944

In [35]:
np.linalg.matrix_rank(D)

4

In [36]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

1.10

In [37]:
D_inv = np.where((D_inv<0),0,1)
D_inv

array([[1, 1, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [1, 0, 1, 0]])

In [45]:
E = np.where((D_inv==1),B,C)
E

array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])

### Задание 2 

In [39]:
a = np.array([[1,6],
              [2,8],
              [3,11],
              [3,10],
              [1,7]])

In [40]:
mean_a = np.array([a[:,0].mean(),a[:,1].mean()])
mean_a

array([2. , 8.4])

In [41]:
np.array([a[:,i].mean() for i in range(2)])

array([2. , 8.4])

### Задание 3

In [42]:
a_centered = np.concatenate(((a[:,0]-mean_a[0]).reshape(5,-1),(a[:,1]-mean_a[1]).reshape(5,-1)),axis=1)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 4

In [47]:
a_cenetered_sp = a_centered[:,0] @ a_centered[:,1]
a_cenetered_sp

8.0

In [44]:
np.dot(a_centered[:,0],a_centered[:,1])

8.0

In [68]:
a_cenetered_sp / 4

2.0